### ISSUE TITLE
create web space and virtual host

### ISSUE THREAD

**Issue by djbpitt** [enb34/alice-in-translation#3]
- [x] Create project group on obdurodon and add all team members and instructors
- [x] Create group-writable setgid directory space on obdurodon with owner
- [x] Create virtual host on obdurodon
- [x] Create "obdurodon" subdirectory for web site files in repo, with dummy index.xhtml file, and upload the file to obdurodon
- [x] Update projects.txt file in course admin folder
- [x] Notify project team and instructors

**Comment by djbpitt** [comment]
Impeded while waiting for information about short name and owner

**Comment by gabikeane** [comment]
@djbpitt 
alice-jpn.obdurodon.org
Dana has volunteered to be owner
