### ISSUE TITLE
Topic modeling/statistical analysis

### ISSUE THREAD

**Issue by mtm80** [enb34/alice-in-translation#7]
Might it be worth using topic modeling for these texts?  The texts that we read earlier this week sounded compelling and perhaps for a work like this, it could reveal something previously unnoticed.

**Comment by danakaufhold** [comment]
I don't really think topic modeling would be useful in our project. We're not analyzing themes in the text or anything like that - we are focusing on linguistic differences at the word or phrase level. Plus there would be an added layer of difficulty defining the topics in both English and Japanese, and I think that would be a lot of work for something that wouldn't necessarily benefit our goals.
